package com.google.android.gms.measurement.internal;

import android.content.Context;
import com.google.android.exoplayer2.C3322C;
import com.google.android.exoplayer2.DefaultRenderersFactory;
import com.google.android.exoplayer2.extractor.ogg.DefaultOggSeeker;
import com.google.android.gms.auth.api.credentials.CredentialsApi;
import com.google.android.gms.common.util.VisibleForTesting;
import com.google.firebase.iid.ServiceStarter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import net.sqlcipher.database.SQLiteDatabase;
import org.apache.commons.lang3.time.DateUtils;

@VisibleForTesting
/* loaded from: classes2.dex */
public final class zzat {
    public static zzem<Long> zzaa;
    public static zzem<Integer> zzab;
    public static zzem<Long> zzac;
    public static zzem<Integer> zzad;
    public static zzem<Integer> zzae;
    public static zzem<Integer> zzaf;
    public static zzem<Integer> zzag;
    public static zzem<Integer> zzah;
    public static zzem<Long> zzai;
    public static zzem<Boolean> zzaj;
    public static zzem<String> zzak;
    public static zzem<Long> zzal;
    public static zzem<Integer> zzam;
    public static zzem<Double> zzan;
    public static zzem<Integer> zzao;
    public static zzem<Integer> zzap;
    public static zzem<Boolean> zzaq;
    public static zzem<Boolean> zzar;
    public static zzem<Boolean> zzas;
    public static zzem<Boolean> zzat;
    public static zzem<Boolean> zzau;
    public static zzem<Boolean> zzav;
    public static zzem<Boolean> zzaw;
    public static zzem<Boolean> zzax;
    public static zzem<Boolean> zzay;
    public static zzem<Boolean> zzaz;
    public static zzem<Long> zzb;
    public static zzem<Boolean> zzba;
    public static zzem<Boolean> zzbb;
    public static zzem<Boolean> zzbc;
    public static zzem<Boolean> zzbd;
    public static zzem<Boolean> zzbe;
    public static zzem<Boolean> zzbf;
    public static zzem<Boolean> zzbg;
    public static zzem<Boolean> zzbh;
    public static zzem<Boolean> zzbi;
    public static zzem<Boolean> zzbj;
    public static zzem<Boolean> zzbk;
    public static zzem<Boolean> zzbl;
    public static zzem<Boolean> zzbm;
    public static zzem<Boolean> zzbn;
    public static zzem<Boolean> zzbo;
    public static zzem<Boolean> zzbp;
    public static zzem<Boolean> zzbq;
    public static zzem<Boolean> zzbr;
    public static zzem<Boolean> zzbs;
    public static zzem<Boolean> zzbt;
    public static zzem<Boolean> zzbu;
    public static zzem<Boolean> zzbv;
    public static zzem<Boolean> zzbw;
    public static zzem<Boolean> zzbx;
    public static zzem<Boolean> zzby;
    public static zzem<Boolean> zzbz;
    public static zzem<Long> zzc;
    public static zzem<Boolean> zzca;
    public static zzem<Boolean> zzcb;
    public static zzem<Boolean> zzcc;
    public static zzem<Boolean> zzcd;
    public static zzem<Boolean> zzce;
    public static zzem<Boolean> zzcf;
    public static zzem<Boolean> zzcg;
    public static zzem<Boolean> zzch;
    public static zzem<Boolean> zzci;
    public static zzem<Boolean> zzcj;
    public static zzem<Boolean> zzck;
    public static zzem<Long> zzcl;
    public static zzem<Boolean> zzcm;
    public static zzem<Boolean> zzcn;
    public static zzem<Boolean> zzco;
    public static zzem<Boolean> zzcp;
    public static zzem<Integer> zzcq;
    public static zzem<Boolean> zzcr;
    public static zzem<Boolean> zzcs;
    public static zzem<Boolean> zzct;
    private static zzem<Boolean> zzcw;
    public static zzem<String> zzd;
    public static zzem<String> zze;
    public static zzem<Integer> zzf;
    public static zzem<Integer> zzg;
    public static zzem<Integer> zzh;
    public static zzem<Integer> zzi;
    public static zzem<Integer> zzj;
    public static zzem<Integer> zzk;
    public static zzem<Integer> zzl;
    public static zzem<Integer> zzm;
    public static zzem<Integer> zzn;
    public static zzem<Integer> zzo;
    public static zzem<String> zzp;
    public static zzem<Long> zzq;
    public static zzem<Long> zzr;
    public static zzem<Long> zzs;
    public static zzem<Long> zzt;
    public static zzem<Long> zzu;
    public static zzem<Long> zzv;
    public static zzem<Long> zzw;
    public static zzem<Long> zzx;
    public static zzem<Long> zzy;
    public static zzem<Long> zzz;
    private static List<zzem<?>> zzcu = Collections.synchronizedList(new ArrayList());
    private static Set<zzem<?>> zzcv = Collections.synchronizedSet(new HashSet());
    public static zzem<Long> zza = zza("measurement.ad_id_cache_time", 10000L, 10000L, zzas.zza);

    static {
        Long lValueOf = Long.valueOf(DateUtils.MILLIS_PER_DAY);
        zzb = zza("measurement.monitoring.sample_period_millis", lValueOf, lValueOf, zzav.zza);
        Long lValueOf2 = Long.valueOf(DateUtils.MILLIS_PER_HOUR);
        zzc = zza("measurement.config.cache_time", lValueOf, lValueOf2, zzbe.zza);
        zzd = zza("measurement.config.url_scheme", "https", "https", zzbr.zza);
        zze = zza("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", zzca.zza);
        zzf = zza("measurement.upload.max_bundles", 100, 100, zzcn.zza);
        Integer numValueOf = Integer.valueOf(C3322C.DEFAULT_BUFFER_SEGMENT_SIZE);
        zzg = zza("measurement.upload.max_batch_size", numValueOf, numValueOf, zzcw.zza);
        zzh = zza("measurement.upload.max_bundle_size", numValueOf, numValueOf, zzdj.zza);
        Integer numValueOf2 = Integer.valueOf(CredentialsApi.ACTIVITY_RESULT_ADD_ACCOUNT);
        zzi = zza("measurement.upload.max_events_per_bundle", numValueOf2, numValueOf2, zzds.zza);
        Integer numValueOf3 = Integer.valueOf(DefaultOggSeeker.MATCH_BYTE_RANGE);
        zzj = zza("measurement.upload.max_events_per_day", numValueOf3, numValueOf3, zzef.zza);
        zzk = zza("measurement.upload.max_error_events_per_day", numValueOf2, numValueOf2, zzau.zza);
        Integer numValueOf4 = Integer.valueOf(SQLiteDatabase.SQLITE_MAX_LIKE_PATTERN_LENGTH);
        zzl = zza("measurement.upload.max_public_events_per_day", numValueOf4, numValueOf4, zzax.zza);
        zzm = zza("measurement.upload.max_conversions_per_day", 10000, 10000, zzaw.zza);
        zzn = zza("measurement.upload.max_realtime_events_per_day", 10, 10, zzaz.zza);
        zzo = zza("measurement.store.max_stored_events_per_app", numValueOf3, numValueOf3, zzay.zza);
        zzp = zza("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", zzbb.zza);
        zzq = zza("measurement.upload.backoff_period", 43200000L, 43200000L, zzba.zza);
        zzr = zza("measurement.upload.window_interval", lValueOf2, lValueOf2, zzbd.zza);
        zzs = zza("measurement.upload.interval", lValueOf2, lValueOf2, zzbc.zza);
        zzt = zza("measurement.upload.realtime_upload_interval", 10000L, 10000L, zzbf.zza);
        zzu = zza("measurement.upload.debug_upload_interval", 1000L, 1000L, zzbh.zza);
        zzv = zza("measurement.upload.minimum_delay", 500L, 500L, zzbg.zza);
        zzw = zza("measurement.alarm_manager.minimum_interval", 60000L, 60000L, zzbj.zza);
        zzx = zza("measurement.upload.stale_data_deletion_interval", lValueOf, lValueOf, zzbi.zza);
        zzy = zza("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, zzbl.zza);
        zzz = zza("measurement.upload.initial_upload_delay_time", 15000L, 15000L, zzbk.zza);
        zzaa = zza("measurement.upload.retry_time", 1800000L, 1800000L, zzbn.zza);
        zzab = zza("measurement.upload.retry_count", 6, 6, zzbm.zza);
        zzac = zza("measurement.upload.max_queue_time", 2419200000L, 2419200000L, zzbp.zza);
        zzad = zza("measurement.lifetimevalue.max_currency_tracked", 4, 4, zzbo.zza);
        zzae = zza("measurement.audience.filter_result_max_count", 200, 200, zzbq.zza);
        zzaf = zza("measurement.upload.max_public_user_properties", 25, 25, null);
        Integer numValueOf5 = Integer.valueOf(ServiceStarter.ERROR_UNKNOWN);
        zzag = zza("measurement.upload.max_event_name_cardinality", numValueOf5, numValueOf5, null);
        zzah = zza("measurement.upload.max_public_event_params", 25, 25, null);
        Long lValueOf3 = Long.valueOf(DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
        zzai = zza("measurement.service_client.idle_disconnect_millis", lValueOf3, lValueOf3, zzbt.zza);
        Boolean bool = Boolean.FALSE;
        zzaj = zza("measurement.test.boolean_flag", bool, bool, zzbs.zza);
        zzak = zza("measurement.test.string_flag", "---", "---", zzbv.zza);
        zzal = zza("measurement.test.long_flag", -1L, -1L, zzbu.zza);
        zzam = zza("measurement.test.int_flag", -2, -2, zzbx.zza);
        Double dValueOf = Double.valueOf(-3.0d);
        zzan = zza("measurement.test.double_flag", dValueOf, dValueOf, zzbw.zza);
        zzao = zza("measurement.experiment.max_ids", 50, 50, zzbz.zza);
        zzap = zza("measurement.max_bundles_per_iteration", 100, 100, zzby.zza);
        zzaq = zza("measurement.validation.internal_limits_internal_event_params", bool, bool, zzcb.zza);
        Boolean bool2 = Boolean.TRUE;
        zzar = zza("measurement.referrer.enable_logging_install_referrer_cmp_from_apk", bool2, bool2, zzcd.zza);
        zzas = zza("measurement.collection.firebase_global_collection_flag_enabled", bool2, bool2, zzcc.zza);
        zzat = zza("measurement.collection.efficient_engagement_reporting_enabled_2", bool2, bool2, zzcf.zza);
        zzau = zza("measurement.collection.redundant_engagement_removal_enabled", bool, bool, zzce.zza);
        zzav = zza("measurement.client.freeride_engagement_fix", bool2, bool2, zzch.zza);
        zzaw = zza("measurement.collection.log_event_and_bundle_v2", bool2, bool2, zzcg.zza);
        zzax = zza("measurement.quality.checksum", bool, bool, null);
        zzay = zza("measurement.sdk.dynamite.allow_remote_dynamite2", bool, bool, zzcj.zza);
        zzaz = zza("measurement.sdk.collection.validate_param_names_alphabetical", bool2, bool2, zzci.zza);
        zzba = zza("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, bool, zzcl.zza);
        zzbb = zza("measurement.audience.refresh_event_count_filters_timestamp", bool, bool, zzck.zza);
        zzbc = zza("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, bool, zzcm.zza);
        zzbd = zza("measurement.sdk.collection.retrieve_deeplink_from_bow_2", bool2, bool2, zzcp.zza);
        zzbe = zza("measurement.sdk.collection.last_deep_link_referrer2", bool2, bool2, zzco.zza);
        zzbf = zza("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, bool, zzcr.zza);
        zzbg = zza("measurement.sdk.collection.last_gclid_from_referrer2", bool, bool, zzcq.zza);
        zzbh = zza("measurement.sdk.collection.enable_extend_user_property_size", bool2, bool2, zzct.zza);
        zzbi = zza("measurement.upload.file_lock_state_check", bool, bool, zzcs.zza);
        zzbj = zza("measurement.ga.ga_app_id", bool, bool, zzcv.zza);
        zzbk = zza("measurement.lifecycle.app_backgrounded_tracking", bool2, bool2, zzcu.zza);
        zzbl = zza("measurement.lifecycle.app_in_background_parameter", bool, bool, zzcx.zza);
        zzbm = zza("measurement.integration.disable_firebase_instance_id", bool, bool, zzcz.zza);
        zzbn = zza("measurement.lifecycle.app_backgrounded_engagement", bool, bool, zzcy.zza);
        zzbo = zza("measurement.collection.service.update_with_analytics_fix", bool, bool, zzdb.zza);
        zzbp = zza("measurement.service.use_appinfo_modified", bool, bool, zzda.zza);
        zzbq = zza("measurement.client.firebase_feature_rollout.v1.enable", bool2, bool2, zzdd.zza);
        zzbr = zza("measurement.client.sessions.check_on_reset_and_enable2", bool2, bool2, zzdc.zza);
        zzbs = zza("measurement.scheduler.task_thread.cleanup_on_exit", bool, bool, zzdf.zza);
        zzbt = zza("measurement.upload.file_truncate_fix", bool, bool, zzde.zza);
        zzbu = zza("measurement.sdk.referrer.delayed_install_referrer_api", bool, bool, zzdh.zza);
        zzbv = zza("measurement.sdk.screen.disabling_automatic_reporting", bool2, bool2, zzdg.zza);
        zzbw = zza("measurement.sdk.screen.manual_screen_view_logging", bool2, bool2, zzdi.zza);
        zzbx = zza("measurement.gold.enhanced_ecommerce.format_logs", bool2, bool2, zzdl.zza);
        zzby = zza("measurement.gold.enhanced_ecommerce.nested_param_daily_event_count", bool2, bool2, zzdk.zza);
        zzbz = zza("measurement.gold.enhanced_ecommerce.upload_nested_complex_events", bool2, bool2, zzdn.zza);
        zzca = zza("measurement.gold.enhanced_ecommerce.log_nested_complex_events", bool2, bool2, zzdm.zza);
        zzcb = zza("measurement.gold.enhanced_ecommerce.updated_schema.client", bool2, bool2, zzdp.zza);
        zzcc = zza("measurement.gold.enhanced_ecommerce.updated_schema.service", bool2, bool2, zzdo.zza);
        zzcw = zza("measurement.collection.synthetic_data_mitigation", bool, bool, zzdr.zza);
        zzcd = zza("measurement.service.configurable_service_limits", bool2, bool2, zzdq.zza);
        zzce = zza("measurement.client.configurable_service_limits", bool2, bool2, zzdt.zza);
        zzcf = zza("measurement.androidId.delete_feature", bool2, bool2, zzdv.zza);
        zzcg = zza("measurement.client.global_params", bool2, bool2, zzdu.zza);
        zzch = zza("measurement.service.global_params", bool2, bool2, zzdx.zza);
        zzci = zza("measurement.service.global_params_in_payload", bool2, bool2, zzdw.zza);
        zzcj = zza("measurement.client.string_reader", bool2, bool2, zzdz.zza);
        zzck = zza("measurement.sdk.attribution.cache", bool2, bool2, zzdy.zza);
        zzcl = zza("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, zzeb.zza);
        zzcm = zza("measurement.service.database_return_empty_collection", bool2, bool2, zzea.zza);
        zzcn = zza("measurement.service.ssaid_removal", bool2, bool2, zzed.zza);
        zzco = zza("measurement.client.consent_state_v1", bool, bool, zzec.zza);
        zzcp = zza("measurement.service.consent_state_v1_W33", bool, bool, zzee.zza);
        zzcq = zza("measurement.service.storage_consent_support_version", 203290, 203290, zzeh.zza);
        zzcr = zza("measurement.client.ad_impression.dev", bool, bool, zzeg.zza);
        zzcs = zza("measurement.service.ad_impression", bool, bool, zzej.zza);
        zzct = zza("measurement.service.separate_public_internal_event_blacklisting", bool, bool, zzei.zza);
    }

    public static Map<String, String> zza(Context context) {
        com.google.android.gms.internal.measurement.zzco zzcoVarZza = com.google.android.gms.internal.measurement.zzco.zza(context.getContentResolver(), com.google.android.gms.internal.measurement.zzdd.zza("com.google.android.gms.measurement"));
        return zzcoVarZza == null ? Collections.emptyMap() : zzcoVarZza.zza();
    }

    @VisibleForTesting
    private static <V> zzem<V> zza(String str, V v8, V v9, zzek<V> zzekVar) {
        zzem<V> zzemVar = new zzem<>(str, v8, v9, zzekVar);
        zzcu.add(zzemVar);
        return zzemVar;
    }
}
